import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/navbar";
import Footer from "~/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // Default site title and a template so child pages can provide a short
  // title and inherit the branded suffix automatically.
  title: {
    default: "TechnoCast: Metals & Alloys",
    template: "%s - TechnoCast: Metals & Alloys",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Fixed navbar overlay */}
        <div className="fixed top-4 left-1/2 transform -translate-x-1/2 z-50 w-full max-w-6xl px-4">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
